# Generated by Django 5.1.4 on 2024-12-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('supertype', models.TextField()),
                ('subtypes', models.TextField(blank=True, null=True)),
                ('types', models.TextField(blank=True, null=True)),
                ('number', models.TextField()),
                ('rarity', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'card',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('updated_at', models.DateField()),
                ('market', models.TextField()),
            ],
            options={
                'db_table': 'market',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('series', models.TextField()),
                ('printed_total', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('ptcgo_code', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('symbol_url', models.TextField(blank=True, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'set',
                'managed': False,
            },
        ),
    ]
